### ISSUE TITLE
Runewords and Sigil of Absolution bug (esp. Xis)

### ISSUE THREAD

**Issue by darkchrome021** [Median-XL/Issue-Tracker#14]
After putting a Xis runeword on an item, then applied Sigil of Absolution (Occult Effigy), it does increase +Requirements, but the level requirement does not decrease to -5. Please fix, Thank you.

![17ef60d16b18e8b990f091bf72d1f8bc](https://user-images.githubusercontent.com/56901083/67347795-b2210d00-f575-11e9-827b-5a4eae1de37b.png)

![vON4UAh](https://user-images.githubusercontent.com/56901083/67347818-c2d18300-f575-11e9-9821-a3998d2e0fe7.png)

**Comment by GavinK88** [comment]
Fixed for 1.4
