### ISSUE TITLE
2BUG Terror Strike on 6fi weapon runeword

### ISSUE THREAD

**Issue by terrorbugs** [Median-XL/Issue-Tracker#21]
1st bug: not always proc at 1st hit 3-6 if luck
2st bug: grim presece off after 7-15 sec after buff this skill
please fix terror strike before patch 1.6. this very cool hiden mechanic old paladin ty.

**Comment by terrorbugs** [comment]
P.S. this mechanic only use with swap weapons like buff from shamanka, i use this on unholy melee paladin to kill uldy tell me if it not bug.

**Comment by terrorbugs** [comment]
video with bugs https://www.youtube.com/watch?v=t97nEEhQJOE

**Comment by GavinK88** [comment]
Issues already addressed by SB (i.e. 2nd not a bug)
