### ISSUE TITLE
Can't Equip Moon Symbol's Into 3rd/4th Belt Row Slots

### ISSUE THREAD

**Issue by atom0s** [Median-XL/Issue-Tracker#25]
**Diablo 2 Version:** 1.14d LoD
**Median XL Version:** 1.6.1
**Renderer Used:** 3DFX Glide

**Bug Description:**

Unlocked Sorceress' Ennead skill to create the Moon Symbols. However, they can't be equipped into the 3rd and 4th slots of belts that are T3/T4 etc. like normal potions. 

This appears to only affect manually trying to drag them into the slots. You can still shift+click them into the slots otherwise.

_(On a side note, the 3/4th slots with Median seem to be very glitchy/laggy when trying to use them manually at all.)_

**Comment by GavinK88** [comment]
Moon cookies removed
