### ISSUE TITLE
consistent game freeze when dying in teganze 1.7 sigma

### ISSUE THREAD

**Issue by Stofferen** [Median-XL/Issue-Tracker#28]
after 1.7, my game stops responding when i die in teganze, using a 150 melee sorc, on a win10 64 bit system.

my game freezes at the frame just before the frame that should show 0hp and the "you died" screen.

**Comment by GavinK88** [comment]
Does this issue still occur since the 1.7.2 hotfix? (1.7.1 should've addressed the likely cause of it)

**Comment by Stofferen** [comment]
it does appear to be fixed now, yes :)
