### ISSUE TITLE
Sanguine Covenant buff (2% amulet proc version) grants no cold/fire pierce

### ISSUE THREAD

**Issue by Vanarchy** [Median-XL/Issue-Tracker#31]
Exact mod that can roll on rare amulets: "2% Chance to cast level 43 Sanguine Covenant on Kill".
D2Stats shows no changes to the pierce percentages when you get the buff. There are no tangible damage increases either.
My pierce is very far from being capped and most of my damage is cold - if it worked, I would notice.

**Comment by GavinK88** [comment]
The fire and cold pierce bonus is not granted by soft points, this is intentional.
