### ISSUE TITLE
Hellfire aura scroll not compatibly with Dark Pact

### ISSUE THREAD

**Issue by Fricc88** [Median-XL/Issue-Tracker#38]
Hi,

As title. Enchanted the helm and since then when I equip it, I get the Bloodbath bonus only for 2-3 seconds then it goes away and only Hellfire aura stays.-

This should not be the case as it means this helmet is not usable like this.... Unsocketing the scroll from the helm would be nice so at least its not lost TG in the meantime.

@Fricc

Please correct.

Cheers

**Comment by GavinK88** [comment]
scrolls removed
