### ISSUE TITLE
Item: Hellmouth (+ Parasite levels wont stack with Necros Parasite level)

### ISSUE THREAD

**Issue by acidwarrior27** [Median-XL/Issue-Tracker#40]
Hi,
is the title says, when equiping the Hellmouth gloves, the "+12 Parasite" create a dedicated skill and do NOT ADD to my parasite level. 

Intentional?

**Comment by SebastianRiechert** [comment]
probably yes, since the hellmouth parasite skill is different from the necro parasite skill (it doesn't require a scythe or dagger)

**Comment by GavinK88** [comment]
What Sebastian said
