### ISSUE TITLE
BUG Scroll of Enchantment: Helmet - Level 5 Hellfire Aura

### ISSUE THREAD

**Issue by SEMallEoN** [Median-XL/Issue-Tracker#41]
Endless Pride... Because of a bug, I ruined an expensive item.
Before the scroll was applied, it gave a +2 to All Skills Total Character Defense +50% Maximum Elemental Resists +3%
After using the scroll, gains +3 to maximum fire resistance. The rest of the max resistance and +2 to All Skills Total Character Defense +50% is not added. Although before using the scroll it was +3 to all and gave a +2 AS +50% TCD.

**Comment by GavinK88** [comment]
scrolls removed
