### ISSUE TITLE
Flying Polar Buffalo Error appearing in place of the actual RW

### ISSUE THREAD

**Issue by Fallinghope** [Median-XL/Issue-Tracker#43]
As the title states, I was trying to create the Rune Word 'Elementalist'. After Putting 3 jewels into the druid helm, followed by a Shaad Rune, the rune word was 'Flying Polar Buffalo Error'. Not sure what caused it to bug like that. Just trying to see if I may have done something wrong. Any help is appreciated.

**Comment by GavinK88** [comment]
RW removed
