### ISSUE TITLE
 BUG: Scroll of Enhancement: Class Charm and Nexus Crystal not adding stats

### ISSUE THREAD

**Issue by Tazz1542** [Median-XL/Issue-Tracker#45]
I used the:

{**Scroll** **of Enchantment: Class Charm Cube Reagent
Cube with the Nexus Crystal to Add Bonus
Enhances Your Innate Skill
9% Less Mana Drained When Hit
Damage Absorption increased by 20%** }

on my sorceress' Nexus Crystal and the new stats of 9 % less mana and 20% does not appear on the item but now says "Already Enchanted"
Are the stats hidden?

**Comment by GavinK88** [comment]
scrolls removed
