### ISSUE TITLE
Rathma Square Level Req

### ISSUE THREAD

**Issue by GavinK88** [Median-XL/Issue-Tracker#5]
Rathma Square in Caldeum not showing as red when below required level to enter
https://i.imgur.com/OKvgHNr.jpg

Originally reported on forum by another user.

**Comment by marcoMXL** [comment]
Just Rathma square though? There shouldn't be anything different with this one and the rest

**Comment by GavinK88** [comment]
Yeah seemingly just Rathma Square, can confirm still present

**Comment by marcoMXL** [comment]
bug seems very random, may be related to door object
