### ISSUE TITLE
Pressing ESC on Inventory Opens S&E Screen

### ISSUE THREAD

**Issue by Seekers98** [Median-XL/Issue-Tracker#8]
... opens save and exit screen and toggles automap off

Was not the case in vanilla, esc would just close the tab. Some people also get Save and Exit menu when doing this but not everyone. 
Case in point: https://clips.twitch.tv/embed?clip=BoxyAverageSashimiDeIlluminati
Above clip is from 1.2

**Comment by marcoMXL** [comment]
fixed in 1.3
